In [1]:
import torch


In [2]:
x = torch.tensor(3.0)
y = torch.tensor([2.0,2.0])
z=  torch.tensor([2.0])

In [3]:
x.shape

torch.Size([])

In [4]:
y.shape

torch.Size([2])

In [5]:
z.shape

torch.Size([1])

In [6]:
len(y)

2

In [7]:
import tensorflow as tf
#from tensorflow.examples.tutorials.mnist import input_data
#mnist = input_data.read_data_sets('C:\\Users\\cj00677\\OneDrive - University of Surrey\\Desktop\\d2l_practice', one_hot=True, validation_size=0)

from tensorflow.keras.datasets import mnist
mnist.load_data(path = 'C:\\Users\\cj00677\\OneDrive - University of Surrey\\Desktop\\d2l_practice\\asd')

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [8]:
tf.__version__

'2.8.0'

In [9]:
A = torch.arange(20).reshape(5, 4)


In [10]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])

In [11]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [12]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [13]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [15]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [17]:
id(A),id(B)

(2328175512368, 2328175510288)

In [18]:
A=torch.tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]])

In [19]:
b=A.clone() #deep

In [20]:
A[0][0]=10

In [21]:
A

tensor([[10.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [22]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [23]:
A=torch.tensor([ 0.,  1.,  2.,  3.])

In [24]:
B=A.clone()

In [25]:
B

tensor([0., 1., 2., 3.])

In [26]:
A[0]=10

In [27]:
B

tensor([0., 1., 2., 3.])

In [28]:
A = torch.arange(20.).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A + B


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [29]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [30]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [31]:
x = torch.arange(4, dtype=torch.float32)

In [32]:
x.sum()

tensor(6.)

In [33]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [34]:
A.shape, A.sum()


(torch.Size([5, 4]), tensor(190.))

In [35]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [36]:
A.sum(axis=(0, 1)) #A.sum(axis=[0, 1])

tensor(190.)

In [37]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [38]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [39]:
x

tensor([0., 1., 2., 3.])

In [40]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [41]:
torch.sum(x * y)

tensor(6.)

In [42]:
A.shape, x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [43]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [44]:
x

tensor([0., 1., 2., 3.])

In [45]:
#torch.mv(A,x)

In [46]:
#torch.mv(x,A.T)

In [47]:
#torch.mv(x,x)

In [48]:

#AA=torch.tensor([[ 0.,  1.,  2.,  3.],
#        [ 4.,  5.,  6.,  7.],
#        [ 8.,  9., 10., 11.],
#        [12., 13., 14., 15.]])

In [49]:
#torch.mv(AA,AA)

In [50]:
#torch.mv(A,A)
#vector + matrix @ vector expected, got 1, 2, 2
#       =        *                       d  d  d

In [51]:
B = torch.ones(4, 3)

In [52]:
B.shape

torch.Size([4, 3])

In [53]:
A.shape

torch.Size([5, 4])

In [54]:
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [55]:
#torch.dot(A,A)
#1D tensors expected, but got 2D and 2D tensors

In [56]:
x*x 


tensor([0., 1., 4., 9.])

In [57]:
A*A

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [58]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [59]:
torch.abs(u).sum()

tensor(7.)

In [60]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [62]:
import os
os.makedirs(os.path.join('', 'data'), exist_ok=True)
data_file = os.path.join('', 'data', 'house_tiny.csv')

In [63]:
import pandas as pd
data = pd.read_csv(data_file)

In [64]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

In [65]:
type(inputs),type(outputs)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [66]:
inputs = inputs.fillna(inputs.mean())

In [67]:
type(inputs)

pandas.core.frame.DataFrame

In [68]:
inputs = pd.get_dummies(inputs, dummy_na=True)

In [69]:
type(inputs)

pandas.core.frame.DataFrame

In [70]:
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [71]:
outputs

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

In [72]:
type(inputs),type(outputs)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [84]:
torch.tensor([6.]).item()

6.0

In [91]:
sum_A = A.sum(axis=0, keepdims=True)

In [92]:
sum_A 

tensor([[40., 45., 50., 55.]])

In [93]:
A/sum_A

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [97]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [98]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [99]:
torch.abs(u)

tensor([3., 4.])

In [100]:
torch.abs(u).sum()

tensor(7.)

In [101]:
torch.norm(torch.ones((4, 9)))

tensor(6.)