In [1]:
import torch


In [2]:
x = torch.arange(12.)

In [3]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
X.shape

torch.Size([3, 4])

In [8]:
x.numel()

12

In [9]:
X[0][0]=111

In [10]:
X 

tensor([[111.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

In [11]:
x

tensor([111.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])

In [12]:
x.reshape(3, -1)

tensor([[111.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

In [13]:
x.reshape(-1, 4)

tensor([[111.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

In [14]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.randn(3, 4)

tensor([[ 0.7947, -0.6297,  2.1223, -1.0377],
        [ 0.2698,  0.6874, -1.4185, -0.6408],
        [ 1.3419, -0.8772,  0.2615,  1.4602]])

In [16]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
torch.tensor(1).item()

1

In [18]:
torch.tensor([[1]]).item()

1

In [19]:
torch.tensor([[[1],[1]]]).shape

torch.Size([1, 2, 1])

In [20]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

# diff between transpose and view

In [22]:
a=torch.randn(1, 2, 3, 4)

In [23]:
 b = a.transpose(1, 2)

In [24]:
a.size()

torch.Size([1, 2, 3, 4])

In [25]:
b.size()

torch.Size([1, 3, 2, 4])

In [26]:
c = a.view(1, 3, 2, 4)

In [27]:
c.size()

torch.Size([1, 3, 2, 4])

In [28]:
c 

tensor([[[[-0.0477,  0.1982, -0.9993,  0.4193],
          [-0.7400, -1.0262,  0.1475,  0.4617]],

         [[-2.2870,  0.1268, -2.0389, -0.8427],
          [-1.2792,  0.3730, -0.5120,  0.8302]],

         [[-1.0130, -0.2496,  0.3194, -0.4621],
          [ 0.1525,  1.0736,  2.1575, -1.3493]]]])

In [29]:
a

tensor([[[[-0.0477,  0.1982, -0.9993,  0.4193],
          [-0.7400, -1.0262,  0.1475,  0.4617],
          [-2.2870,  0.1268, -2.0389, -0.8427]],

         [[-1.2792,  0.3730, -0.5120,  0.8302],
          [-1.0130, -0.2496,  0.3194, -0.4621],
          [ 0.1525,  1.0736,  2.1575, -1.3493]]]])

In [30]:
b

tensor([[[[-0.0477,  0.1982, -0.9993,  0.4193],
          [-1.2792,  0.3730, -0.5120,  0.8302]],

         [[-0.7400, -1.0262,  0.1475,  0.4617],
          [-1.0130, -0.2496,  0.3194, -0.4621]],

         [[-2.2870,  0.1268, -2.0389, -0.8427],
          [ 0.1525,  1.0736,  2.1575, -1.3493]]]])

In [31]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [33]:
before = id(Y)
Y = Y + X
id(Y) == before
id(Y),before

(2703059732496, 2703505976992)

In [34]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

id(Z): 2703506032576


In [35]:
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2703506032576


In [36]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [37]:
id(X)

2703506014912

In [38]:
id(A)

2703505824048

In [39]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [40]:
import os

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [41]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [42]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [43]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


numpy.ndarray to torch.tensor : torch.tensor(numpy.ndarray)

    B = torch.tensor(A)
    
torch.tensor to numpy.ndarray :  torch.tensor.numpy()

    A = X.numpy()
    
pandas.DataFrame to  numpy.ndarray: pandas.DataFrame.to_numpy()
    
    inputs.to_numpy(dtype=float)

In [44]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))